name: "Semgrep Action"
author: "Return To Corporation"
description: "Easily detect and prevent bugs and anti-patterns in your codebase"
runs:
  using: "docker"
  image: "docker://ievans/semgrep-action:0.1-alpha"
branding:
  icon: "align-left"
  color: "gray-dark"
