name: Linters

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  semgrepdep:
    name: semgrepdep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ievans/semgrep-action@develop
        id: semgrepdep
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! ${{join(steps.semgrepdep.outputs.*, '\n')}}'
            })
