name: Tests

on:
  pull_request:
  push:
    branches: [develop]

jobs:

  live-runs:
    name: live run of action on this repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: semgrep-live-registry-id
        name: with a semgrep.live Registry ID
        uses: ./tests/local-image-action
        with:
          config: r/python.jwt
